### PARSER ###

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: dora-parser-deployment
  labels:
    app: dora
spec:
  selector:
    matchLabels:
      app: dora
  replicas: 2 #2 for test
  template:
    metadata:
      labels:
        app: dora
    spec:
      containers:
        - name: dora-parser
          image: dev-dora-dora_parser:latest
          imagePullPolicy: Never
          ports:
          - name: dora-parser
            containerPort: 7000
---
apiVersion: v1
kind: Service
metadata:
  name: dora-parser-service
spec:
  selector:
    app: dora
  ports:
  - name: http
    protocol: TCP
    port: 7000
    targetPort: dora-parser

### BOT ###
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: dora-bot-deployment
  labels:
    app: dora
spec:
  selector:
    matchLabels:
      app: dora
  replicas: 1 #1 for test
  template:
    metadata:
      labels:
        app: dora
    spec:
      containers:
        - name: dora-bot
          image: dev-dora-dora_bot:latest
          imagePullPolicy: Never
          ports:
          - containerPort: 6000
---
apiVersion: v1
kind: Service
metadata:
  name: dora-bot-service
spec:
  selector:
    app: dora
  ports:
  - name: http
    protocol: TCP
    port: 6000
    targetPort: 6000
---

### API ###
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: dora-api-deployment
  labels:
    app: dora
spec:
  selector:
    matchLabels:
      app: dora
  replicas: 1 #1 for test
  template:
    metadata:
      labels:
        app: dora
    spec:
      containers:
        - name: dora-api
          image: dev-dora-dora_api:latest
          imagePullPolicy: Never
          ports:
          - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: dora-api-service
spec:
  type: NodePort
  selector:
    app: dora
  ports:
  - name: http
    protocol: TCP
    port: 9000
    targetPort: 9000
---
