### PARSER ###

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: parser-deployment
  labels:
    app: parser
spec:
  selector:
    matchLabels:
      app: parser
  replicas: 2 #2 for test
  template:
    metadata:
      labels:
        app: parser
    spec:
      containers:
        - name: dora-parser
          image: dev-dora-dora_parser:latest
          imagePullPolicy: Never
          ports:
          - name: dora-parser
            containerPort: 7000
---
apiVersion: v1
kind: Service
metadata:
  name: dora-parser
spec:
  selector:
    app: parser
  ports:
  - port: 7000
    targetPort: dora-parser

### BOT ###
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: bot-deployment
  labels:
    app: bot
spec:
  selector:
    matchLabels:
      app: bot
  replicas: 1 #1 for test
  template:
    metadata:
      labels:
        app: bot
    spec:
      containers:
        - name: dora-bot
          image: dev-dora-dora_bot:latest
          imagePullPolicy: Never
          ports:
          - name: dora-bot
            containerPort: 6000
---
apiVersion: v1
kind: Service
metadata:
  name: dora-bot
spec:
  selector:
    app: bot
  ports:
  - port: 6000
    targetPort: dora-bot
---

### API ###
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
spec:
  selector:
    matchLabels:
      app: api
  replicas: 1 #1 for test
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: dora-api
          image: dev-dora-dora_api:latest
          imagePullPolicy: Never
          ports:
          - name: dora-api
            containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: dora-api
spec:
  type: NodePort
  selector:
    app: api
  ports:
  - port: 9000
    targetPort: dora-api
---
